name: "vercel-cypress"
description: "Run Cypress tests against a Vercel deployment"
branding:
  icon: "alert-circle"
  color: "green"
inputs:
  vercel-token:
    description: "Vercel API token"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/run.sh
      shell: bash
